security:
  basic:
    enabled: false
    
noon:
  acme:
    url: https://tornyak.com
    basepath: ${noon.acme.url}/acme
    nonceSize: 16

spring:
  mvc:
    favicon:
      enabled: false
      
logging:
  level:
    root: info
    com.tornyak.noon: debug
